### ISSUE TITLE
unknown flag: --application

### ISSUE THREAD

**Issue by PierrickP** [omegion/argocd-actions#16]
**Describe the bug**

Hello, we have an error since a couple of days when we use on github action.
I noticed some changes recently. I moved from `omegion/argocd-app-actions@master` to `omegion/argocd-actions@v1` but still not works.

Which version can we use ?

```
name: Deploy Staging

on:
  push:
    branches:
      - develop

jobs:
  build_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Re-Deploy my app
        uses: omegion/argocd-actions@v1
        with:
          address: 'my.argocd.com'
          token: ${{ secrets.ARGOCD_STAGING_AUTH }}
          appName: 'my-app'
``` 

**To Reproduce**

1. Run 
The github action step run the following command (logged on Github action)

```docker run --rm -i ghcr.io/omegion/argocd-actions:v1 \        
    --application=my_application \
    --token=my_token \
    --address=my_argocd_address \
    --logLevel=debug
```
3. See error
```
Unable to find image 'ghcr.io/omegion/argocd-actions:v1' locally
v1: Pulling from omegion/argocd-actions
8663204ce13b: Pull complete 
45c2c68bc0f7: Pull complete 
Digest: sha256:d1655a36cd13bcbc696e663c15753e4edefe1c45af0f18269ebba639999908be
Status: Downloaded newer image for ghcr.io/omegion/argocd-actions:v1
Error: unknown flag: --application
```
